### ISSUE TITLE
1080p videos have no sound

### ISSUE THREAD

**Issue by telegrambotdev** [eidoriantan/youtube-downloader#1]
When we click convert & download after selecting 1080p format,still 1080p videos doesnt have sound,after we downloaded.can you fix it ?

**Comment by eidoriantan** [comment]
>Typically 1080p or better videos do not have audio encoded with it. The audio must be downloaded separately and merged via an encoding library.

I'd just read this from [here](https://www.npmjs.com/package/ytdl-core#handling-separate-streams). Thank you for reporting this!

**Comment by eidoriantan** [comment]
Users are now able to choose video and audio formats separately then both medias are merged.

7050b71
